name: Build & Publish

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# IMAGE_NAME global dihapus dari sini karena akan diatur secara dinamis di dalam job

jobs:
  build:
    runs-on: ubuntu-latest

    # really important for ensuring that the package inherits the permissions of the repo
    # https://stackoverflow.com/questions/77092191/use-github-to-change-visibility-of-ghcr-io-package
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Mengubah nama repositori menjadi huruf kecil dan menyimpannya ke GITHUB_ENV
      - name: Convert image name to lowercase
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # create a unique tag for each build for debugging
      - name: Set Docker tag
        id: date
        run: echo "DATE_STAMP=$(date +%s)" >> "$GITHUB_ENV"

      - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}
            ${{ env.IMAGE_NAME }}:latest
